version: '3'

services:
  gateway-api:
    image: restaurant/gateway
    build: 
      context: ./gateway/restaurant-gateway/
      dockerfile: Dockerfile.local
    ports: 
      - "8080:8080"

  identity-api:
    image: restaurant/identity
    build: ./services/identity.api/
    depends_on:
       - pgsql

  menu-api:
    image: restaurant/menu
    build: 
      context: ./services/menu.api/
      dockerfile: Dockerfile.local
    depends_on:
       - pgsql

  basket-api:
    image: restaurant/basket
    build: ./services/basket.api/
    depends_on:
      - redis

  order-api:
    image: restaurant/order
    build: 
      context: ./services/order.api
      dockerfile: Dockerfile.local
    depends_on:
      - pgsql

  pgsql:
    image: postgres:alpine
    volumes: 
      - database-data:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine
    
volumes:
  database-data: