# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/mobile/*
    - azure-pipelines.yml
pr: none

jobs:
- job: Android
  pool:
    vmImage: 'windows-latest'
  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  steps:
  
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/Restaurant.Client.sln'
  # - task: CacheBeta@0
  #   inputs:
  #     key: |
  #       $(Agent.OS)
  #       $(Build.SourcesDirectory)
  #     path: $(NUGET_PACKAGES)
  #   displayName: Cache NuGet packages
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/Restaurant.Droid.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'
      msbuildVersionOption: 'latest'
      msbuildArchitectureOption: 'x64'
      jdkOption: 'JDKVersion'
      msbuildArguments: /p:JavaSdkDirectory="$(JAVA_HOME)/"

- job: iOS
  pool:
    vmImage: 'macOS-10.14'
  variables:
    buildConfiguration: 'Release'
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  steps:
  - bash: |
      SYMLINK=6_0_0
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_0_0
    displayName: Selecting Xamarin.iOS
    
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.301'
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.301'
    
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/Restaurant.Client.sln'
  # - task: CacheBeta@0
  #   inputs:
  #     key: |
  #       $(Agent.OS)
  #       $(Build.SourcesDirectory)
  #     path: $(NUGET_PACKAGES)
  #   displayName: Cache NuGet packages
  - task: XamariniOS@2
    inputs:
      solutionFile: '**/Restaurant.iOS.csproj'
      configuration: 'Release'
      buildForSimulator: true
      packageApp: false