apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - order-pgsql.yaml
  - http-route.yaml

configMapGenerator:
  - envs:
      - config.env
    name: order-api

secretGenerator:
  - envs:
      - .env.secret
    name: order-api

images:
  - name: order-api
    newName: ghcr.io/chayxana/order-api
    newTag: 1.0.9
