version: '3.7'

services:
  order-api:
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://order-db:5432/orderdb
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=Passw0rd!

  basket-api:
    environment:
      - REDIS_HOST=redis
      - IDENTITY_URL=http://identity-api
      - IDENTITY_URL_PUB=http://localhost:8080/identity
      - BASE_PATH=/basket

  catalog-api:
    environment:
      - DATABASE_URL=postgres://admin:Passw0rd!@catalog-db:5432/catalogdb
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - BASE_URL=/catalog

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=identity-db
      - DB_NAME=identity_database
      - DB_USER=admin
      - DB_PASSWORD=Passw0rd!
      - PATH_BASE=/identity
      - MENU_API_URL=http://localhost:8080/menu
      - ORDER_API_URL=http://localhost:8080/order
      - BASKET_API_URL=http://localhost:8080/basket
      - DASHBOARD_APP_URL=http://localhost:8080/dashboard
      - IDENTITY_URL_PUB=http://localhost:8080/identity

  order-db:
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_USER=admin
      - PGDATA=/pg
      - POSTGRES_DB=orderdb

  identity-db:
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_USER=admin
      - PGDATA=/pg
      - POSTGRES_DB=identity_database


  catalog-db:
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_USER=admin
      - POSTGRES_DB=catalogdb