version: '3.7'

services:
  nginx:
    image: restaurant/nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - menu-api
      - dashboard-app
      - identity-api
      - basket-api
      - order-api

  identity-api:
    image: restaurant/identity
    build: ./services/identity.api/
    depends_on:
       - pgsql
    ports: 
      - "5000:80"

  menu-api:
    image: restaurant/menu
    build: 
      context: ./services/menu.api/
      dockerfile: local.Dockerfile
    depends_on:
       - pgsql

  basket-api:
    image: restaurant/basket
    build: ./services/basket.api/
    depends_on:
      - redis

  order-api:
    image: restaurant/order
    build: 
      context: ./services/order.api
      dockerfile: local.Dockerfile
    depends_on:
      - pgsql

  dashboard-app:
    image: restaurant/dashboard
    build:
      context: ./web/web.admin/dashboard
      dockerfile: local.Dockerfile

  # web-app:
  #   image: restaurant/web
  #   build:
  #     context: ./web/web.client/web-app
  #     dockerfile: local.Dockerfile
      
  pgsql:
    image: postgres:alpine
    volumes: 
      - database-data:/var/lib/postgresql/data
    ports: 
      - "5433:5432"
    
  redis:
    image: redis:alpine
    
volumes:
  database-data: