server:
  port: 8090
  tomcat:
    max-threads: 5
  use-forward-headers: true

# Spring Boot initialization time improvements
spring:
  main:
    lazy-initialization: true
  jmx:
    enabled: true
  application:
    name: order-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_orders_database
    username: jurabek
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL:http://localhost:5100}
          jwk-set-uri: ${AUTH_URL:http://localhost:5100}/.well-known/openid-configuration/jwks
          
# logging:
#   level:
#     org:
#       springframework:
#         web: DEBUG
#         boot:
#           autoconfigure: DEBUG

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: [env,beans,health,info]
    health:
      show-details: always
      
service-registry:
  basket-api:
    url: ${BASKET_URL:http://localhost:5200}


