apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- envs:
  - config.env
  name: payment-api

images:
- name: payment-api
  newName: ghcr.io/chayxana/payment-api
  newTag: 0.0.7
