---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
  labels: 
    app: dashboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      containers:
      - image: jurabek/dashboard
        imagePullPolicy: Never
        name: dashboard-app
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "60m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - image: jurabek/basket
        imagePullPolicy: Never
        name: basket-api
        ports:
        - containerPort: 5200
        env:
        - name: IDENTITY_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: identity
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: REDIS_HOST
          value: redis-data:6379
        - name: BASE_PATH
          value: /basket
        resources:
          requests:
            memory: "32Mi"
            cpu: "60m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        image: jurabek/identity
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: OrchestrationType
          value: k8s
        - name: PATH_BASE
          value: /identity
        - name: BASKET_API_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: basket_pub
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: MENU_API_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: menu_pub
        - name: ORDER_API_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: order_pub
        - name: DASHBOARD_APP_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: dashboard_pub
        - name: ConnectionStrings__IdentityConnectionString
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: identity__ConnectionString
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-api
  template:
    metadata:
      labels:
        app: menu-api
    spec:
      containers:
      - name: menu-api
        image: jurabek/menu
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: PATH_BASE
          value: /menu
        - name: OrchestrationType
          value: k8s
        - name: ConnectionStrings__MenuDatabaseConnectionString
          valueFrom:
           configMapKeyRef:
             name: local-config
             key: menu__ConnectionString
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: IDENTITY_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: identity
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - image: jurabek/order
        imagePullPolicy: Never
        name: order-api
        ports:
          - containerPort: 8090
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /order
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: BASKET_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: basket
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourcePassword
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourceUrl
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourceUserName
        readinessProbe:
          httpGet:
            path: /order/health
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /order/health
            port: 8090
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"