apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- http-route.yaml
- identity-pgsql.yaml

secretGenerator:
- envs:
  - .env.secret
  name: identity-api

configMapGenerator:
- envs:
  - config.env
  name: identity-api
images:
- name: identity-api
  newName: ghcr.io/chayxana/identity-api
  newTag: 0.0.5
