apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- redis.yaml
- virtual-service.yaml

configMapGenerator:
- envs:
  - config.env
  name: basket-api

images:
- name: basket-api
  newName: jurabek/basket
  newTag: 0.0.3
