apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- order-pgsql.yaml
- virtual-service.yaml

configMapGenerator:
- envs:
  - config.env
  name: order-api

images:
- name: basket-api
  newName: order
  newTag: 1.0.3
- name: order-api
  newName: order
  newTag: 0.0.0
