#Will start the gateway server @8080
server:
  port: 8080

spring:
  application:
    name: restaurant-gateway

#Zuul routes.
zuul:
  routes:
    menu:
      path: /menu/**
      sensitiveHeaders:
      url: ${MENU_URL:http://localhost:5000}
    order:
      path: /order/**
      url: ${ORDER_URL:http://localhost:8090}
    identity:
      path: /identity/**
      sensitiveHeaders:
      url: ${IDENTITY_URL:http://localhost:5100}
    basket:
      path: /basket/**
      url: ${BASKET_URL:http://localhost:5200}
  host:
        connect-timeout-millis: 60000
        socket-timeout-millis: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  