apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

configMapGenerator:
- behavior: merge
  envs:
  - config.env
  name: basket-api
resources:
- ../base
patches:
- path: http_route_patch.yaml
