name: build-release

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      docker-file:
        required: false
        type: string
        default: Dockerfile
  
    outputs:
      new-version:
        value: ${{ jobs.build-and-release.outputs.new-version }}
      current-version:
        value: ${{ jobs.build-and-release.outputs.current-version }}
      
jobs:
  build-and-release:
    outputs:
      new-version: ${{ steps.version.outputs.new-version }}
      current-version: ${{ steps.version.outputs.current-version }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Bump Version"
        if: github.ref == 'refs/heads/develop'
        id: version
        uses: ./.github/actions/bump-version
        with:
          service-name: ./src/backend/services/${{ inputs.service-name }}

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: |
            # Disable latest tag
            latest=true
          images: |
            name=ghcr.io/chayxana/${{ inputs.service-name }}
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.version.outputs.new-version }}
            type=sha

      - name: Determine build metadata
        id: build-metadata
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Essentially just ignore the cache output (PR can't write to registry cache)
            echo "cache-to=type=local,dest=/tmp/discard,ignore-error=true" >> $GITHUB_OUTPUT
          else
            echo "cache-to=type=registry,mode=max,ref=ghcr.io/chayxana/${{ inputs.service-name }}:build-cache" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: src/backend/services/${{ inputs.service-name }}
          file: src/backend/services/${{ inputs.service-name }}/${{ inputs.docker-file }}
          push: ${{ steps.build-metadata.outputs.push }}
          tags: ${{ steps.metadata.outputs.tags }} 
          cache-from: type=registry,ref=ghcr.io/chayxana/${{ inputs.service-name }}:build-cache
          cache-to: ${{ steps.build-metadata.outputs.cache-to }}
          platforms: linux/amd64,linux/arm64

      - name: "Commit bumped version"
        if: github.ref == 'refs/heads/develop'
        uses: ./.github/actions/git-commit
        with:
          git-message: Bumped ${{ inputs.service-name }} version from  ${{ steps.version.outputs.current-version }} to ${{ steps.version.outputs.new-version }}
          directory: ./src/backend/services/${{ inputs.service-name }}
          origin-branch: ${{ github.ref }}

      - name: "Push changes"
        if: github.ref == 'refs/heads/develop'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
