name: catalog-api

on:
  push:
    branches:
    - develop
    paths:
    - "src/backend/services/catalog.api/**"
    - ".github/workflows/catalog-api.yml"
  pull_request:
    branches:
    - develop
    paths:
    - "src/backend/services/catalog-api/**"
    - ".github/workflows/catalog-api.yml"

env:
  SERVICE_NAME: catalog-api

jobs:
  build-and-release:
    outputs:
      new-version: ${{ steps.version.outputs.new-version }}
      current-version:  ${{ steps.version.outputs.current-version }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch: 0
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Bump Version"
      if: github.ref == 'refs/heads/develop'
      id: version
      uses: ./.github/actions/bump-version
      with:
        service-name: ./src/backend/services/${{ env.SERVICE_NAME }}

    - name: Detect Pull Request
      id: allow_push
      run: |
        BRANCH=${{ github.ref }}
        if [ $BRANCH = 'refs/heads/develop' ]; then
           echo "ALLOW_PUSH=true" >> $GITHUB_OUTPUT
        else
          echo "ALLOW_PUSH=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: src/backend/services/catalog-api
        push: ${{ steps.allow_push.outputs.ALLOW_PUSH }}
        tags: ghcr.io/chayxana/catalog-api:${{ steps.version.outputs.new-version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Commit bumped version"
      if: github.ref == 'refs/heads/develop'
      uses: ./.github/actions/git-commit
      with:
        git-message: Bumped ${{ env.SERVICE_NAME }} version from  ${{ steps.version.outputs.current-version }} to ${{ steps.version.outputs.new-version }}
        directory: ./src/backend/services/${{ env.SERVICE_NAME }}
        origin-branch: ${{ github.ref }}
        
    - name: "Push changes"
      if: github.ref == 'refs/heads/develop'
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}

  update-manifests:
    if: github.ref == 'refs/heads/develop'
    needs:
      - build-and-release
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: catalog-api
      version: ${{ needs.build-and-release.outputs.new-version }}