name: catalog-api

on:
  push:
    branches:
    - develop
    paths:
    - "src/backend/services/catalog-api/**"
    - ".github/workflows/catalog-api.yml"
  pull_request:
    branches:
    - develop
    paths:
    - "src/backend/services/catalog-api/**"
    - ".github/workflows/catalog-api.yml"

jobs:
  build-release:
    uses: ./.github/workflows/build-release.yml
    with:
      service-name: catalog-api
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/develop'
    needs:
      - build-release
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: catalog-api
      version: ${{ needs.build-release.outputs.new-version }}