name: menu-api

on:
  push:
    branches:
    - develop
    paths:
    - 'src/backend/services/order.api/**'
    - '.github/workflows/menu-api.yml'
  pull_request:
    branches:
    - develop
    paths:
    - 'src/backend/services/menu.api/**'
    - '.github/workflows/menu-api.yml'

jobs:
  build-and-test:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Setup cache 
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Menu.API/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: |
          chmod -R +x scripts/
          scripts/build.sh menu_api
        working-directory: ./src/backend/

      - name: Test & QA
        run: |
          chmod -R +x scripts/
          scripts/qa.sh menu_api
        working-directory: ./src/backend/
        env:
          SONAR_TOKEN: ${{ secrets.MENU_API_SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
      
      - name: Upload menu-api artifact
        uses: actions/upload-artifact@v1
        with:
          name: menu_api
          path: ./src/backend/services/menu.api/menu-api-release
        if: matrix.os == 'ubuntu-latest'

  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '0'

    - name: Download basket-api artifact
      uses: actions/download-artifact@v1
      with:
        name: menu_api
    - name: Copy artifact to working directory
      shell: bash
      run: |
        ls -a
        cp -r menu_api/ ./src/backend/services/menu.api/menu-api-release
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jurabek/menu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: release.Dockerfile
        workdir: ./src/backend/services/menu.api

