name: payment-api

on:
  push:
    branches:
    - develop
    paths:
    - "src/backend/services/payment-api/**"
    - ".github/workflows/payment-api.yml"
  pull_request:
    branches:
    - develop
    paths:
    - "src/backend/services/payment-api/**"
    - ".github/workflows/payment-api.yml"

env:
  SERVICE_NAME: payment-api

jobs:
  build-and-release:
    outputs:
      new-version: ${{ steps.version.outputs.new-version }}
      current-version:  ${{ steps.version.outputs.current-version }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch: 0
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Bump Version"
      if: github.ref == 'refs/heads/develop'
      id: version
      uses: ./.github/actions/bump-version
      with:
        service-name: ./src/backend/services/${{ env.SERVICE_NAME }}

    - name: Build
      if: github.ref != 'refs/heads/develop'
      uses: docker/build-push-action@v4
      with:
        context: src/backend/services/${{ env.SERVICE_NAME }}
        push: false
        tags: ghcr.io/chayxana/${{ env.SERVICE_NAME }}:pr-build
        cache-from: type=gha
        cache-to: type=gha,mode=max
      
    - name: Build and Push
      if: github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v4
      with:
        context: src/backend/services/${{ env.SERVICE_NAME }}
        push: true
        tags: ghcr.io/chayxana/${{ env.SERVICE_NAME }}:${{ steps.version.outputs.new-version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Commit bumped version"
      if: github.ref == 'refs/heads/develop'
      uses: ./.github/actions/git-commit
      with:
        git-message: Bumped ${{ env.SERVICE_NAME }} version from  ${{ steps.version.outputs.current-version }} to ${{ steps.version.outputs.new-version }}
        directory: ./src/backend/services/${{ env.SERVICE_NAME }}
        origin-branch: ${{ github.ref }}
        
    - name: "Push changes"
      if: github.ref == 'refs/heads/develop'
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}